#!/usr/bin/perl
use strict;
use warnings;
use File::Spec::Functions;
use FindBin;
use lib catfile($FindBin::Bin, 'lib');
use lib catfile($FindBin::Bin, 'extlib');
use XIRCD;

XIRCD->new()->bootstrap();
